/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcFlowPayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "deactivateMerchant"
      | "feeBps"
      | "feeCollector"
      | "getCustomerPayments"
      | "getMerchant"
      | "getMerchantCount"
      | "getMerchantList"
      | "getMerchantPayments"
      | "getMerchantTotalByToken"
      | "getNextPaymentId"
      | "getPayment"
      | "isRegistered"
      | "owner"
      | "paused"
      | "pay"
      | "pendingOwner"
      | "reactivateMerchant"
      | "registerMerchant"
      | "setFee"
      | "setFeeCollector"
      | "setPaused"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollectorUpdated"
      | "FeeUpdated"
      | "MerchantDeactivated"
      | "MerchantReactivated"
      | "MerchantRegistered"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentMade"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCustomerPayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchantList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchantPayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchantTotalByToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateMerchant",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerMerchant",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCustomerPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchantList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchantPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchantTotalByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newCollector: AddressLike];
  export type OutputTuple = [newCollector: string];
  export interface OutputObject {
    newCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantDeactivatedEvent {
  export type InputTuple = [merchant: AddressLike];
  export type OutputTuple = [merchant: string];
  export interface OutputObject {
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantReactivatedEvent {
  export type InputTuple = [merchant: AddressLike];
  export type OutputTuple = [merchant: string];
  export interface OutputObject {
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantRegisteredEvent {
  export type InputTuple = [
    merchant: AddressLike,
    name: string,
    category: string
  ];
  export type OutputTuple = [merchant: string, name: string, category: string];
  export interface OutputObject {
    merchant: string;
    name: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentMadeEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    customer: AddressLike,
    merchant: AddressLike,
    token: AddressLike,
    grossAmount: BigNumberish,
    fee: BigNumberish,
    netAmount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    customer: string,
    merchant: string,
    token: string,
    grossAmount: bigint,
    fee: bigint,
    netAmount: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    customer: string;
    merchant: string;
    token: string;
    grossAmount: bigint;
    fee: bigint;
    netAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcFlowPay extends BaseContract {
  connect(runner?: ContractRunner | null): ArcFlowPay;
  waitForDeployment(): Promise<this>;

  interface: ArcFlowPayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  deactivateMerchant: TypedContractMethod<
    [merchant: AddressLike],
    [void],
    "nonpayable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getCustomerPayments: TypedContractMethod<
    [customer: AddressLike],
    [bigint[]],
    "view"
  >;

  getMerchant: TypedContractMethod<
    [wallet: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        name: string;
        category: string;
        active: boolean;
        registeredAt: bigint;
        paymentCount: bigint;
      }
    ],
    "view"
  >;

  getMerchantCount: TypedContractMethod<[], [bigint], "view">;

  getMerchantList: TypedContractMethod<[], [string[]], "view">;

  getMerchantPayments: TypedContractMethod<
    [merchant: AddressLike],
    [bigint[]],
    "view"
  >;

  getMerchantTotalByToken: TypedContractMethod<
    [merchant: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getNextPaymentId: TypedContractMethod<[], [bigint], "view">;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, bigint, string] & {
        customer: string;
        merchant: string;
        token: string;
        grossAmount: bigint;
        fee: bigint;
        netAmount: bigint;
        timestamp: bigint;
        memo: string;
      }
    ],
    "view"
  >;

  isRegistered: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pay: TypedContractMethod<
    [
      merchant: AddressLike,
      token: AddressLike,
      grossAmount: BigNumberish,
      memo: string
    ],
    [bigint],
    "nonpayable"
  >;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  reactivateMerchant: TypedContractMethod<[], [void], "nonpayable">;

  registerMerchant: TypedContractMethod<
    [name: string, category: string],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;

  setFeeCollector: TypedContractMethod<
    [_collector: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[value: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateMerchant"
  ): TypedContractMethod<[merchant: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCustomerPayments"
  ): TypedContractMethod<[customer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMerchant"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        name: string;
        category: string;
        active: boolean;
        registeredAt: bigint;
        paymentCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMerchantCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMerchantList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMerchantPayments"
  ): TypedContractMethod<[merchant: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMerchantTotalByToken"
  ): TypedContractMethod<
    [merchant: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, bigint, string] & {
        customer: string;
        merchant: string;
        token: string;
        grossAmount: bigint;
        fee: bigint;
        netAmount: bigint;
        timestamp: bigint;
        memo: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<
    [
      merchant: AddressLike,
      token: AddressLike,
      grossAmount: BigNumberish,
      memo: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateMerchant"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerMerchant"
  ): TypedContractMethod<
    [name: string, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_collector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MerchantDeactivated"
  ): TypedContractEvent<
    MerchantDeactivatedEvent.InputTuple,
    MerchantDeactivatedEvent.OutputTuple,
    MerchantDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MerchantReactivated"
  ): TypedContractEvent<
    MerchantReactivatedEvent.InputTuple,
    MerchantReactivatedEvent.OutputTuple,
    MerchantReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MerchantRegistered"
  ): TypedContractEvent<
    MerchantRegisteredEvent.InputTuple,
    MerchantRegisteredEvent.OutputTuple,
    MerchantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentMade"
  ): TypedContractEvent<
    PaymentMadeEvent.InputTuple,
    PaymentMadeEvent.OutputTuple,
    PaymentMadeEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "MerchantDeactivated(address)": TypedContractEvent<
      MerchantDeactivatedEvent.InputTuple,
      MerchantDeactivatedEvent.OutputTuple,
      MerchantDeactivatedEvent.OutputObject
    >;
    MerchantDeactivated: TypedContractEvent<
      MerchantDeactivatedEvent.InputTuple,
      MerchantDeactivatedEvent.OutputTuple,
      MerchantDeactivatedEvent.OutputObject
    >;

    "MerchantReactivated(address)": TypedContractEvent<
      MerchantReactivatedEvent.InputTuple,
      MerchantReactivatedEvent.OutputTuple,
      MerchantReactivatedEvent.OutputObject
    >;
    MerchantReactivated: TypedContractEvent<
      MerchantReactivatedEvent.InputTuple,
      MerchantReactivatedEvent.OutputTuple,
      MerchantReactivatedEvent.OutputObject
    >;

    "MerchantRegistered(address,string,string)": TypedContractEvent<
      MerchantRegisteredEvent.InputTuple,
      MerchantRegisteredEvent.OutputTuple,
      MerchantRegisteredEvent.OutputObject
    >;
    MerchantRegistered: TypedContractEvent<
      MerchantRegisteredEvent.InputTuple,
      MerchantRegisteredEvent.OutputTuple,
      MerchantRegisteredEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentMade(uint256,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;
    PaymentMade: TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
