/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcFlowSplitInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_MEMBERS"
      | "acceptOwnership"
      | "cancelSplit"
      | "createSplit"
      | "getGroup"
      | "getGroupCount"
      | "getGroupMembers"
      | "getOutstandingShare"
      | "getRefundable"
      | "getUserGroups"
      | "isMember"
      | "joinSplit"
      | "lockGroup"
      | "owner"
      | "paused"
      | "payShare"
      | "pendingOwner"
      | "setPaused"
      | "settle"
      | "transferOwnership"
      | "withdrawRefund"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GroupCancelled"
      | "GroupCreated"
      | "GroupLocked"
      | "GroupSettled"
      | "MemberAdded"
      | "MemberJoined"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "Refunded"
      | "SharePaid"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_MEMBERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSplit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSplit",
    values: [
      string,
      AddressLike,
      AddressLike,
      AddressLike[],
      BigNumberish[],
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingShare",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRefundable",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGroups",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinSplit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockGroup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRefund",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_MEMBERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGroup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGroupCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGroupMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRefundable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGroups",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinSplit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockGroup", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payShare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRefund",
    data: BytesLike
  ): Result;
}

export namespace GroupCancelledEvent {
  export type InputTuple = [groupId: BigNumberish];
  export type OutputTuple = [groupId: bigint];
  export interface OutputObject {
    groupId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupCreatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    creator: AddressLike,
    token: AddressLike,
    recipient: AddressLike,
    name: string,
    openJoin: boolean
  ];
  export type OutputTuple = [
    groupId: bigint,
    creator: string,
    token: string,
    recipient: string,
    name: string,
    openJoin: boolean
  ];
  export interface OutputObject {
    groupId: bigint;
    creator: string;
    token: string;
    recipient: string;
    name: string;
    openJoin: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupLockedEvent {
  export type InputTuple = [groupId: BigNumberish, committed: BigNumberish];
  export type OutputTuple = [groupId: bigint, committed: bigint];
  export interface OutputObject {
    groupId: bigint;
    committed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupSettledEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    member: AddressLike,
    share: BigNumberish
  ];
  export type OutputTuple = [groupId: bigint, member: string, share: bigint];
  export interface OutputObject {
    groupId: bigint;
    member: string;
    share: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    member: AddressLike,
    share: BigNumberish
  ];
  export type OutputTuple = [groupId: bigint, member: string, share: bigint];
  export interface OutputObject {
    groupId: bigint;
    member: string;
    share: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    member: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [groupId: bigint, member: string, amount: bigint];
  export interface OutputObject {
    groupId: bigint;
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharePaidEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    member: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [groupId: bigint, member: string, amount: bigint];
  export interface OutputObject {
    groupId: bigint;
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcFlowSplit extends BaseContract {
  connect(runner?: ContractRunner | null): ArcFlowSplit;
  waitForDeployment(): Promise<this>;

  interface: ArcFlowSplitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_MEMBERS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  cancelSplit: TypedContractMethod<
    [groupId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSplit: TypedContractMethod<
    [
      name: string,
      token: AddressLike,
      recipient: AddressLike,
      members: AddressLike[],
      shares: BigNumberish[],
      openJoin: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getGroup: TypedContractMethod<
    [groupId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        creator: string;
        recipient: string;
        token: string;
        name: string;
        committed: bigint;
        collected: bigint;
        memberCount: bigint;
        paidCount: bigint;
        status: bigint;
        openJoin: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getGroupCount: TypedContractMethod<[], [bigint], "view">;

  getGroupMembers: TypedContractMethod<
    [groupId: BigNumberish],
    [
      [string[], bigint[], bigint[], boolean[]] & {
        wallets: string[];
        shares: bigint[];
        paidAmounts: bigint[];
        paid: boolean[];
      }
    ],
    "view"
  >;

  getOutstandingShare: TypedContractMethod<
    [groupId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getRefundable: TypedContractMethod<
    [groupId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getUserGroups: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  isMember: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  joinSplit: TypedContractMethod<
    [groupId: BigNumberish, share: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockGroup: TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payShare: TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  setPaused: TypedContractMethod<[value: boolean], [void], "nonpayable">;

  settle: TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawRefund: TypedContractMethod<
    [groupId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_MEMBERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelSplit"
  ): TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSplit"
  ): TypedContractMethod<
    [
      name: string,
      token: AddressLike,
      recipient: AddressLike,
      members: AddressLike[],
      shares: BigNumberish[],
      openJoin: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGroup"
  ): TypedContractMethod<
    [groupId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        creator: string;
        recipient: string;
        token: string;
        name: string;
        committed: bigint;
        collected: bigint;
        memberCount: bigint;
        paidCount: bigint;
        status: bigint;
        openJoin: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGroupCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGroupMembers"
  ): TypedContractMethod<
    [groupId: BigNumberish],
    [
      [string[], bigint[], bigint[], boolean[]] & {
        wallets: string[];
        shares: bigint[];
        paidAmounts: bigint[];
        paid: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutstandingShare"
  ): TypedContractMethod<
    [groupId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRefundable"
  ): TypedContractMethod<
    [groupId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserGroups"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinSplit"
  ): TypedContractMethod<
    [groupId: BigNumberish, share: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockGroup"
  ): TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payShare"
  ): TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRefund"
  ): TypedContractMethod<[groupId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "GroupCancelled"
  ): TypedContractEvent<
    GroupCancelledEvent.InputTuple,
    GroupCancelledEvent.OutputTuple,
    GroupCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GroupCreated"
  ): TypedContractEvent<
    GroupCreatedEvent.InputTuple,
    GroupCreatedEvent.OutputTuple,
    GroupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GroupLocked"
  ): TypedContractEvent<
    GroupLockedEvent.InputTuple,
    GroupLockedEvent.OutputTuple,
    GroupLockedEvent.OutputObject
  >;
  getEvent(
    key: "GroupSettled"
  ): TypedContractEvent<
    GroupSettledEvent.InputTuple,
    GroupSettledEvent.OutputTuple,
    GroupSettledEvent.OutputObject
  >;
  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "SharePaid"
  ): TypedContractEvent<
    SharePaidEvent.InputTuple,
    SharePaidEvent.OutputTuple,
    SharePaidEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "GroupCancelled(uint256)": TypedContractEvent<
      GroupCancelledEvent.InputTuple,
      GroupCancelledEvent.OutputTuple,
      GroupCancelledEvent.OutputObject
    >;
    GroupCancelled: TypedContractEvent<
      GroupCancelledEvent.InputTuple,
      GroupCancelledEvent.OutputTuple,
      GroupCancelledEvent.OutputObject
    >;

    "GroupCreated(uint256,address,address,address,string,bool)": TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;
    GroupCreated: TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;

    "GroupLocked(uint256,uint256)": TypedContractEvent<
      GroupLockedEvent.InputTuple,
      GroupLockedEvent.OutputTuple,
      GroupLockedEvent.OutputObject
    >;
    GroupLocked: TypedContractEvent<
      GroupLockedEvent.InputTuple,
      GroupLockedEvent.OutputTuple,
      GroupLockedEvent.OutputObject
    >;

    "GroupSettled(uint256,address,uint256)": TypedContractEvent<
      GroupSettledEvent.InputTuple,
      GroupSettledEvent.OutputTuple,
      GroupSettledEvent.OutputObject
    >;
    GroupSettled: TypedContractEvent<
      GroupSettledEvent.InputTuple,
      GroupSettledEvent.OutputTuple,
      GroupSettledEvent.OutputObject
    >;

    "MemberAdded(uint256,address,uint256)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberJoined(uint256,address,uint256)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Refunded(uint256,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "SharePaid(uint256,address,uint256)": TypedContractEvent<
      SharePaidEvent.InputTuple,
      SharePaidEvent.OutputTuple,
      SharePaidEvent.OutputObject
    >;
    SharePaid: TypedContractEvent<
      SharePaidEvent.InputTuple,
      SharePaidEvent.OutputTuple,
      SharePaidEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
