/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcFlowSplitInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSplit"
      | "getGroup"
      | "getGroupCount"
      | "getGroupMembers"
      | "getUserGroups"
      | "groupMembers"
      | "groups"
      | "isMember"
      | "owner"
      | "settleShare"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GroupCreated"
      | "GroupSettled"
      | "MemberAdded"
      | "Settled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createSplit",
    values: [string, AddressLike[], BigNumberish[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGroupMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserGroups",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "groupMembers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "groups",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "settleShare",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGroup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGroupCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGroupMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserGroups",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "groupMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "groups", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace GroupCreatedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    creator: AddressLike,
    name: string,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    groupId: bigint,
    creator: string,
    name: string,
    totalAmount: bigint
  ];
  export interface OutputObject {
    groupId: bigint;
    creator: string;
    name: string;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GroupSettledEvent {
  export type InputTuple = [groupId: BigNumberish];
  export type OutputTuple = [groupId: bigint];
  export interface OutputObject {
    groupId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    member: AddressLike,
    share: BigNumberish
  ];
  export type OutputTuple = [groupId: bigint, member: string, share: bigint];
  export interface OutputObject {
    groupId: bigint;
    member: string;
    share: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettledEvent {
  export type InputTuple = [
    groupId: BigNumberish,
    member: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [groupId: bigint, member: string, amount: bigint];
  export interface OutputObject {
    groupId: bigint;
    member: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcFlowSplit extends BaseContract {
  connect(runner?: ContractRunner | null): ArcFlowSplit;
  waitForDeployment(): Promise<this>;

  interface: ArcFlowSplitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSplit: TypedContractMethod<
    [
      name: string,
      members: AddressLike[],
      shares: BigNumberish[],
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  getGroup: TypedContractMethod<
    [groupId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        creator: string;
        name: string;
        totalAmount: bigint;
        memberCount: bigint;
        settledCount: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getGroupCount: TypedContractMethod<[], [bigint], "view">;

  getGroupMembers: TypedContractMethod<
    [groupId: BigNumberish],
    [
      [string[], bigint[], boolean[]] & {
        wallets: string[];
        shares: bigint[];
        paid: boolean[];
      }
    ],
    "view"
  >;

  getUserGroups: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  groupMembers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean, bigint] & {
        wallet: string;
        share: bigint;
        paid: boolean;
        paidAt: bigint;
      }
    ],
    "view"
  >;

  groups: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        creator: string;
        name: string;
        totalAmount: bigint;
        memberCount: bigint;
        settledCount: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  isMember: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  settleShare: TypedContractMethod<
    [groupId: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSplit"
  ): TypedContractMethod<
    [
      name: string,
      members: AddressLike[],
      shares: BigNumberish[],
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGroup"
  ): TypedContractMethod<
    [groupId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        creator: string;
        name: string;
        totalAmount: bigint;
        memberCount: bigint;
        settledCount: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGroupCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGroupMembers"
  ): TypedContractMethod<
    [groupId: BigNumberish],
    [
      [string[], bigint[], boolean[]] & {
        wallets: string[];
        shares: bigint[];
        paid: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserGroups"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "groupMembers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean, bigint] & {
        wallet: string;
        share: bigint;
        paid: boolean;
        paidAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "groups"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        creator: string;
        name: string;
        totalAmount: bigint;
        memberCount: bigint;
        settledCount: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settleShare"
  ): TypedContractMethod<
    [groupId: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "GroupCreated"
  ): TypedContractEvent<
    GroupCreatedEvent.InputTuple,
    GroupCreatedEvent.OutputTuple,
    GroupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GroupSettled"
  ): TypedContractEvent<
    GroupSettledEvent.InputTuple,
    GroupSettledEvent.OutputTuple,
    GroupSettledEvent.OutputObject
  >;
  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "Settled"
  ): TypedContractEvent<
    SettledEvent.InputTuple,
    SettledEvent.OutputTuple,
    SettledEvent.OutputObject
  >;

  filters: {
    "GroupCreated(uint256,address,string,uint256)": TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;
    GroupCreated: TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;

    "GroupSettled(uint256)": TypedContractEvent<
      GroupSettledEvent.InputTuple,
      GroupSettledEvent.OutputTuple,
      GroupSettledEvent.OutputObject
    >;
    GroupSettled: TypedContractEvent<
      GroupSettledEvent.InputTuple,
      GroupSettledEvent.OutputTuple,
      GroupSettledEvent.OutputObject
    >;

    "MemberAdded(uint256,address,uint256)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "Settled(uint256,address,uint256)": TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
    Settled: TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
  };
}
