/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcFlowPayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateMerchant"
      | "feeBps"
      | "feeCollector"
      | "getMerchant"
      | "getMerchantCount"
      | "merchantList"
      | "merchants"
      | "owner"
      | "pay"
      | "registerMerchant"
      | "setFee"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MerchantDeactivated"
      | "MerchantRegistered"
      | "Payment"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchantCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merchantList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "merchants",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMerchant",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deactivateMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merchants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace MerchantDeactivatedEvent {
  export type InputTuple = [merchant: AddressLike];
  export type OutputTuple = [merchant: string];
  export interface OutputObject {
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantRegisteredEvent {
  export type InputTuple = [merchant: AddressLike, name: string];
  export type OutputTuple = [merchant: string, name: string];
  export interface OutputObject {
    merchant: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentEvent {
  export type InputTuple = [
    from: AddressLike,
    merchant: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    merchant: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    from: string;
    merchant: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcFlowPay extends BaseContract {
  connect(runner?: ContractRunner | null): ArcFlowPay;
  waitForDeployment(): Promise<this>;

  interface: ArcFlowPayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateMerchant: TypedContractMethod<
    [merchant: AddressLike],
    [void],
    "nonpayable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getMerchant: TypedContractMethod<
    [wallet: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        name: string;
        category: string;
        active: boolean;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;

  getMerchantCount: TypedContractMethod<[], [bigint], "view">;

  merchantList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  merchants: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean, bigint, bigint] & {
        wallet: string;
        name: string;
        category: string;
        active: boolean;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pay: TypedContractMethod<
    [merchant: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerMerchant: TypedContractMethod<
    [name: string, category: string],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateMerchant"
  ): TypedContractMethod<[merchant: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMerchant"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        name: string;
        category: string;
        active: boolean;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMerchantCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "merchantList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "merchants"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean, bigint, bigint] & {
        wallet: string;
        name: string;
        category: string;
        active: boolean;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pay"
  ): TypedContractMethod<
    [merchant: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerMerchant"
  ): TypedContractMethod<
    [name: string, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MerchantDeactivated"
  ): TypedContractEvent<
    MerchantDeactivatedEvent.InputTuple,
    MerchantDeactivatedEvent.OutputTuple,
    MerchantDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MerchantRegistered"
  ): TypedContractEvent<
    MerchantRegisteredEvent.InputTuple,
    MerchantRegisteredEvent.OutputTuple,
    MerchantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Payment"
  ): TypedContractEvent<
    PaymentEvent.InputTuple,
    PaymentEvent.OutputTuple,
    PaymentEvent.OutputObject
  >;

  filters: {
    "MerchantDeactivated(address)": TypedContractEvent<
      MerchantDeactivatedEvent.InputTuple,
      MerchantDeactivatedEvent.OutputTuple,
      MerchantDeactivatedEvent.OutputObject
    >;
    MerchantDeactivated: TypedContractEvent<
      MerchantDeactivatedEvent.InputTuple,
      MerchantDeactivatedEvent.OutputTuple,
      MerchantDeactivatedEvent.OutputObject
    >;

    "MerchantRegistered(address,string)": TypedContractEvent<
      MerchantRegisteredEvent.InputTuple,
      MerchantRegisteredEvent.OutputTuple,
      MerchantRegisteredEvent.OutputObject
    >;
    MerchantRegistered: TypedContractEvent<
      MerchantRegisteredEvent.InputTuple,
      MerchantRegisteredEvent.OutputTuple,
      MerchantRegisteredEvent.OutputObject
    >;

    "Payment(address,address,uint256,uint256)": TypedContractEvent<
      PaymentEvent.InputTuple,
      PaymentEvent.OutputTuple,
      PaymentEvent.OutputObject
    >;
    Payment: TypedContractEvent<
      PaymentEvent.InputTuple,
      PaymentEvent.OutputTuple,
      PaymentEvent.OutputObject
    >;
  };
}
