/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcFlowRecurringInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelRecurring"
      | "createRecurring"
      | "executePayment"
      | "getPayment"
      | "getPaymentCount"
      | "getUserPayments"
      | "isDue"
      | "owner"
      | "payments"
      | "usdc"
      | "userPayments"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RecurringCancelled"
      | "RecurringCreated"
      | "RecurringExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelRecurring",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRecurring",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isDue", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPayments",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelRecurring",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRecurring",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPayments",
    data: BytesLike
  ): Result;
}

export namespace RecurringCancelledEvent {
  export type InputTuple = [paymentId: BigNumberish];
  export type OutputTuple = [paymentId: bigint];
  export interface OutputObject {
    paymentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringCreatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    payer: string,
    payee: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    payer: string;
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringExecutedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    payer: string,
    payee: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    payer: string;
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcFlowRecurring extends BaseContract {
  connect(runner?: ContractRunner | null): ArcFlowRecurring;
  waitForDeployment(): Promise<this>;

  interface: ArcFlowRecurringInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelRecurring: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createRecurring: TypedContractMethod<
    [
      payee: AddressLike,
      amount: BigNumberish,
      frequency: BigNumberish,
      maxExecutions: BigNumberish,
      name: string
    ],
    [bigint],
    "nonpayable"
  >;

  executePayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        payer: string;
        payee: string;
        amount: bigint;
        frequency: bigint;
        nextPayment: bigint;
        totalPaid: bigint;
        executions: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;

  getPaymentCount: TypedContractMethod<[], [bigint], "view">;

  getUserPayments: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  isDue: TypedContractMethod<[paymentId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        payer: string;
        payee: string;
        amount: bigint;
        frequency: bigint;
        startTime: bigint;
        nextPayment: bigint;
        totalPaid: bigint;
        maxExecutions: bigint;
        executions: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userPayments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelRecurring"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createRecurring"
  ): TypedContractMethod<
    [
      payee: AddressLike,
      amount: BigNumberish,
      frequency: BigNumberish,
      maxExecutions: BigNumberish,
      name: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        payer: string;
        payee: string;
        amount: bigint;
        frequency: bigint;
        nextPayment: bigint;
        totalPaid: bigint;
        executions: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPayments"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isDue"
  ): TypedContractMethod<[paymentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        payer: string;
        payee: string;
        amount: bigint;
        frequency: bigint;
        startTime: bigint;
        nextPayment: bigint;
        totalPaid: bigint;
        maxExecutions: bigint;
        executions: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userPayments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "RecurringCancelled"
  ): TypedContractEvent<
    RecurringCancelledEvent.InputTuple,
    RecurringCancelledEvent.OutputTuple,
    RecurringCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecurringCreated"
  ): TypedContractEvent<
    RecurringCreatedEvent.InputTuple,
    RecurringCreatedEvent.OutputTuple,
    RecurringCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RecurringExecuted"
  ): TypedContractEvent<
    RecurringExecutedEvent.InputTuple,
    RecurringExecutedEvent.OutputTuple,
    RecurringExecutedEvent.OutputObject
  >;

  filters: {
    "RecurringCancelled(uint256)": TypedContractEvent<
      RecurringCancelledEvent.InputTuple,
      RecurringCancelledEvent.OutputTuple,
      RecurringCancelledEvent.OutputObject
    >;
    RecurringCancelled: TypedContractEvent<
      RecurringCancelledEvent.InputTuple,
      RecurringCancelledEvent.OutputTuple,
      RecurringCancelledEvent.OutputObject
    >;

    "RecurringCreated(uint256,address,address,uint256)": TypedContractEvent<
      RecurringCreatedEvent.InputTuple,
      RecurringCreatedEvent.OutputTuple,
      RecurringCreatedEvent.OutputObject
    >;
    RecurringCreated: TypedContractEvent<
      RecurringCreatedEvent.InputTuple,
      RecurringCreatedEvent.OutputTuple,
      RecurringCreatedEvent.OutputObject
    >;

    "RecurringExecuted(uint256,address,address,uint256)": TypedContractEvent<
      RecurringExecutedEvent.InputTuple,
      RecurringExecutedEvent.OutputTuple,
      RecurringExecutedEvent.OutputObject
    >;
    RecurringExecuted: TypedContractEvent<
      RecurringExecutedEvent.InputTuple,
      RecurringExecutedEvent.OutputTuple,
      RecurringExecutedEvent.OutputObject
    >;
  };
}
