/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcFlowRecurringInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_KEEPER_REWARD_BPS"
      | "acceptOwnership"
      | "cancelRecurring"
      | "createRecurring"
      | "executePayment"
      | "getGrossAmount"
      | "getNextPaymentId"
      | "getPayeePayments"
      | "getPayerPayments"
      | "getPayment"
      | "isDue"
      | "owner"
      | "paused"
      | "pendingOwner"
      | "setPaused"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "RecurringCancelled"
      | "RecurringCreated"
      | "RecurringExecuted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_KEEPER_REWARD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecurring",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRecurring",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrossAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayeePayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayerPayments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isDue", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_KEEPER_REWARD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecurring",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRecurring",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGrossAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayeePayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayerPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isDue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringCancelledEvent {
  export type InputTuple = [paymentId: BigNumberish];
  export type OutputTuple = [paymentId: bigint];
  export interface OutputObject {
    paymentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringCreatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    payer: AddressLike,
    payee: AddressLike,
    token: AddressLike,
    baseAmount: BigNumberish,
    frequency: BigNumberish,
    keeperRewardBps: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    payer: string,
    payee: string,
    token: string,
    baseAmount: bigint,
    frequency: bigint,
    keeperRewardBps: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    payer: string;
    payee: string;
    token: string;
    baseAmount: bigint;
    frequency: bigint;
    keeperRewardBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringExecutedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    executor: AddressLike,
    baseAmount: BigNumberish,
    keeperReward: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    executor: string,
    baseAmount: bigint,
    keeperReward: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    executor: string;
    baseAmount: bigint;
    keeperReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcFlowRecurring extends BaseContract {
  connect(runner?: ContractRunner | null): ArcFlowRecurring;
  waitForDeployment(): Promise<this>;

  interface: ArcFlowRecurringInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_KEEPER_REWARD_BPS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  cancelRecurring: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createRecurring: TypedContractMethod<
    [
      payee: AddressLike,
      token: AddressLike,
      baseAmount: BigNumberish,
      frequency: BigNumberish,
      maxExecutions: BigNumberish,
      keeperRewardBps: BigNumberish,
      name: string
    ],
    [bigint],
    "nonpayable"
  >;

  executePayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getGrossAmount: TypedContractMethod<
    [paymentId: BigNumberish],
    [bigint],
    "view"
  >;

  getNextPaymentId: TypedContractMethod<[], [bigint], "view">;

  getPayeePayments: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getPayerPayments: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        payer: string;
        payee: string;
        token: string;
        baseAmount: bigint;
        keeperRewardBps: bigint;
        frequency: bigint;
        nextPayment: bigint;
        totalPaid: bigint;
        executions: bigint;
        maxExecutions: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;

  isDue: TypedContractMethod<[paymentId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  setPaused: TypedContractMethod<[value: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_KEEPER_REWARD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRecurring"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createRecurring"
  ): TypedContractMethod<
    [
      payee: AddressLike,
      token: AddressLike,
      baseAmount: BigNumberish,
      frequency: BigNumberish,
      maxExecutions: BigNumberish,
      keeperRewardBps: BigNumberish,
      name: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getGrossAmount"
  ): TypedContractMethod<[paymentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayeePayments"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPayerPayments"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        payer: string;
        payee: string;
        token: string;
        baseAmount: bigint;
        keeperRewardBps: bigint;
        frequency: bigint;
        nextPayment: bigint;
        totalPaid: bigint;
        executions: bigint;
        maxExecutions: bigint;
        active: boolean;
        name: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDue"
  ): TypedContractMethod<[paymentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RecurringCancelled"
  ): TypedContractEvent<
    RecurringCancelledEvent.InputTuple,
    RecurringCancelledEvent.OutputTuple,
    RecurringCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecurringCreated"
  ): TypedContractEvent<
    RecurringCreatedEvent.InputTuple,
    RecurringCreatedEvent.OutputTuple,
    RecurringCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RecurringExecuted"
  ): TypedContractEvent<
    RecurringExecutedEvent.InputTuple,
    RecurringExecutedEvent.OutputTuple,
    RecurringExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RecurringCancelled(uint256)": TypedContractEvent<
      RecurringCancelledEvent.InputTuple,
      RecurringCancelledEvent.OutputTuple,
      RecurringCancelledEvent.OutputObject
    >;
    RecurringCancelled: TypedContractEvent<
      RecurringCancelledEvent.InputTuple,
      RecurringCancelledEvent.OutputTuple,
      RecurringCancelledEvent.OutputObject
    >;

    "RecurringCreated(uint256,address,address,address,uint256,uint8,uint256)": TypedContractEvent<
      RecurringCreatedEvent.InputTuple,
      RecurringCreatedEvent.OutputTuple,
      RecurringCreatedEvent.OutputObject
    >;
    RecurringCreated: TypedContractEvent<
      RecurringCreatedEvent.InputTuple,
      RecurringCreatedEvent.OutputTuple,
      RecurringCreatedEvent.OutputObject
    >;

    "RecurringExecuted(uint256,address,uint256,uint256)": TypedContractEvent<
      RecurringExecutedEvent.InputTuple,
      RecurringExecutedEvent.OutputTuple,
      RecurringExecutedEvent.OutputObject
    >;
    RecurringExecuted: TypedContractEvent<
      RecurringExecutedEvent.InputTuple,
      RecurringExecutedEvent.OutputTuple,
      RecurringExecutedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
