/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ArcFlowPay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArcFlowPay__factory>;
    getContractFactory(
      name: "ArcFlowRecurring",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArcFlowRecurring__factory>;
    getContractFactory(
      name: "ArcFlowSend",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArcFlowSend__factory>;
    getContractFactory(
      name: "ArcFlowSplit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArcFlowSplit__factory>;
    getContractFactory(
      name: "ArcFlowSwap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ArcFlowSwap__factory>;
    getContractFactory(
      name: "IArcFlowSwap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IArcFlowSwap__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2Step__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockFeeOnTransferERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockFeeOnTransferERC20__factory>;
    getContractFactory(
      name: "MockNoReturnERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockNoReturnERC20__factory>;

    getContractAt(
      name: "ArcFlowPay",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArcFlowPay>;
    getContractAt(
      name: "ArcFlowRecurring",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArcFlowRecurring>;
    getContractAt(
      name: "ArcFlowSend",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArcFlowSend>;
    getContractAt(
      name: "ArcFlowSplit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArcFlowSplit>;
    getContractAt(
      name: "ArcFlowSwap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ArcFlowSwap>;
    getContractAt(
      name: "IArcFlowSwap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IArcFlowSwap>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2Step>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockFeeOnTransferERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockFeeOnTransferERC20>;
    getContractAt(
      name: "MockNoReturnERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockNoReturnERC20>;

    deployContract(
      name: "ArcFlowPay",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowPay>;
    deployContract(
      name: "ArcFlowRecurring",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowRecurring>;
    deployContract(
      name: "ArcFlowSend",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowSend>;
    deployContract(
      name: "ArcFlowSplit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowSplit>;
    deployContract(
      name: "ArcFlowSwap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowSwap>;
    deployContract(
      name: "IArcFlowSwap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArcFlowSwap>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockFeeOnTransferERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockFeeOnTransferERC20>;
    deployContract(
      name: "MockNoReturnERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockNoReturnERC20>;

    deployContract(
      name: "ArcFlowPay",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowPay>;
    deployContract(
      name: "ArcFlowRecurring",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowRecurring>;
    deployContract(
      name: "ArcFlowSend",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowSend>;
    deployContract(
      name: "ArcFlowSplit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowSplit>;
    deployContract(
      name: "ArcFlowSwap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ArcFlowSwap>;
    deployContract(
      name: "IArcFlowSwap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IArcFlowSwap>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockFeeOnTransferERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockFeeOnTransferERC20>;
    deployContract(
      name: "MockNoReturnERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockNoReturnERC20>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
